#!/usr/bin/env bash
LATEXTMP="${LATEXTMP:-/tmp}"
# We aren't going to use any ps here, straight conversion from dvi to png/gif
# (it's a little bit ridiculous that the tex filter always converts to ps first)
dvifile=${4#${LATEXTMP}/}
dvifile=${dvifile%.*}.dvi
outfile=${5#${LATEXTMP}/}
outextension=${outfile##*.}
if [[ "${outextension}" == "png" ]]; then
    /usr/local/bin/docker run -i --rm -v ${LATEXTMP}:/doc -w /doc stronk7/docker-texlive-thin \
        /usr/bin/dvipng -T tight ${dvifile} -o ${outfile}
else
    /usr/local/bin/docker run -i --rm -v ${LATEXTMP}:/doc -w /doc stronk7/docker-texlive-thin \
        /usr/bin/dvigif -T tight ${dvifile} -o ${outfile}
fi
