#!/usr/bin/env bash
LATEXTMP="${LATEXTMP:-/tmp}"
echo /usr/local/bin/docker run -i --rm -v ${LATEXTMP}:/doc -w /doc stronk7/docker-texlive-thin /usr/bin/latex "$@"
/usr/local/bin/docker run -i --rm -v ${LATEXTMP}:/doc -w /doc stronk7/docker-texlive-thin \
    /usr/bin/latex "$@"
